// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC_2jcy6FzdF9zk8NqQKdJG6v03vHKhbo',
    appId: '1:359470006752:web:a2c152eefef00b7e93ab85',
    messagingSenderId: '359470006752',
    projectId: 'web-messenger-10d20',
    authDomain: 'web-messenger-10d20.firebaseapp.com',
    storageBucket: 'web-messenger-10d20.firebasestorage.app',
    measurementId: 'G-B483442GEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8cirVeXMCh5paZuy1gcpAmfk-vLnijpk',
    appId: '1:359470006752:android:cbe63cf13096f41a93ab85',
    messagingSenderId: '359470006752',
    projectId: 'web-messenger-10d20',
    storageBucket: 'web-messenger-10d20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB05efa057awmsfpKjBoSxWlrHZovbXJfY',
    appId: '1:359470006752:ios:92cb333e8bdeced493ab85',
    messagingSenderId: '359470006752',
    projectId: 'web-messenger-10d20',
    storageBucket: 'web-messenger-10d20.firebasestorage.app',
    iosBundleId: 'com.example.webMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB05efa057awmsfpKjBoSxWlrHZovbXJfY',
    appId: '1:359470006752:ios:92cb333e8bdeced493ab85',
    messagingSenderId: '359470006752',
    projectId: 'web-messenger-10d20',
    storageBucket: 'web-messenger-10d20.firebasestorage.app',
    iosBundleId: 'com.example.webMessenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC_2jcy6FzdF9zk8NqQKdJG6v03vHKhbo',
    appId: '1:359470006752:web:b501d341e19ff8da93ab85',
    messagingSenderId: '359470006752',
    projectId: 'web-messenger-10d20',
    authDomain: 'web-messenger-10d20.firebaseapp.com',
    storageBucket: 'web-messenger-10d20.firebasestorage.app',
    measurementId: 'G-DGRCXFG9MD',
  );

}